### ISSUE TITLE
error forbidden

### ISSUE THREAD

**Issue by Riokarbu** [Widiskel/sonic-tx-bot#11]
![wdw](https://github.com/user-attachments/assets/20811d96-48f7-4faf-9268-64de659c708d)

yesterday work but now error like this

**Comment by Widiskel** [comment]
its maybe during run time sonic API is on heavy load or Down so you got that error, just try again later

**Comment by Riokarbu** [comment]
@Widiskel bang gw dah tau cara ngakalin forbiden nya, gw coba ngubah script nya jadi run 1 wallet per 1 wallet kek script sebelum update, kalo script yang sekarang baru run 5 menit dah forbiden terus

**Comment by Widiskel** [comment]
klo akunnya terlalu bnyak kyknya emg mending 1 per 1 , soalnya kalo langsung bnyak kena rate limit, alhasil forbidden td

**Comment by Widiskel** [comment]
udh gue tambahin fitur buat pilih mau run langsung banyak atau 1 per 1. gas `git pull` trus `npm update`

**Comment by Riokarbu** [comment]
thanks bang
