### ISSUE TITLE
Is it possible to add a proxy implementation when sending requests to the API to reduce to many requests?

### ISSUE THREAD

**Issue by 0xtbug** [Widiskel/sonic-tx-bot#13]
Hi @Widiskel,

Is it possible to add a proxy implementation when sending requests to the API to reduce to many requests?
I have some proxy lists, I hope you can implement them.

Thanks.

**Comment by Widiskel** [comment]
i already tying to add that feature, but i don't have proxy list that seems to be work, im use this proxy list but many of it should be die
https://github.com/monosans/proxy-list/blob/main/proxies_anonymous/http.txt
