### ISSUE TITLE
Status: Error pubkey.toJSON is not a function, Retrying using Account 3 after 10 Second...

### ISSUE THREAD

**Issue by dsmddsmd** [Widiskel/sonic-tx-bot#16]
Status             : Error pubkey.toJSON is not a function, Retrying using Account 4 after 10 Second...
![Screenshot_561](https://github.com/user-attachments/assets/99d13564-4ebf-41e0-bd2f-52107cb57f95)

**Comment by Widiskel** [comment]
make sure you follow all step, and use private key better than seed pharse
