### ISSUE TITLE
 Status : Error pubkey.toJSON is not a function, Retrying using Account 1 after 10 Second... [ I have used use private key.]

### ISSUE THREAD

**Issue by dsmddsmd** [Widiskel/sonic-tx-bot#18]
![Screenshot_568](https://github.com/user-attachments/assets/b0b934d3-466e-4d75-b2f6-dab6c1f6610b)
![Screenshot_569](https://github.com/user-attachments/assets/af17275d-2f7c-433f-84d3-ede693c33c97)
![Screenshot_570](https://github.com/user-attachments/assets/0538032a-04cf-4872-bc9e-e53cbde1d039)

**Comment by Widiskel** [comment]
mine still run smooth, maybe you miss some step or requirement on setup guide
