### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by copycatcodex** [Widiskel/sonic-tx-bot#21]
please help, pubkey error.
![image](https://github.com/user-attachments/assets/09b1181f-e33b-4c74-9da3-c124ffcf7fbf)

**Comment by copycatcodex** [comment]
![image](https://github.com/user-attachments/assets/48a52d9b-c069-49e4-a77a-64e99d7ef488)
forbidenn error

**Comment by Widiskel** [comment]
that not bot problem , its from sonic it self
