### ISSUE TITLE
I copied private key from backpack wallet and paste in the bot, and I am getting this error

### ISSUE THREAD

**Issue by MrTimonM** [Widiskel/sonic-tx-bot#22]
Choose Your Run Option:   
 
1. Mass Runner. 
2. One By One Runner.     
 
Input your choice : 2     
2
SONIC AUTO TX BOT STARTED
⠦
================= Account 1 =============
Wallet Address     : -
Balance            : - SOL | ? RING
Mystery Box        : -
Daily TX           : -
Status             : Error Non-base58 character, Retrying using Account 1 after 10 Second...

**Comment by Widiskel** [comment]
try use phantom or okx

**Comment by Widiskel** [comment]
and make sure you paste it with correct format like the template file

**Comment by MrTimonM** [comment]
![image](https://github.com/user-attachments/assets/913f6f6d-6e19-451d-9f30-ac2df903b227)

see 
i copied wallet key from phantom

**Comment by Widiskel** [comment]
try to use seed
